const STATUS_OK = "OK";
const STATUS_FAILED = "FAILED";

const ERROR_CODE_AUTOPILOT_FAILED = "AUTOPILOT_FAILED";
const ERROR_CODE_AUTOPILOT_ERROR = "AUTOPILOT_ERROR";

const SECOND_MS = 1000;
const MINUTE_MS = 60000;
const WAIT_POLL_MS = 250;
const REPORT_REFRESH_MS = 30000;

const EXIT_CODE_SUCCESS = 0;
const EXIT_CODE_FAILED = 1;
const EXIT_CODE_INTERRUPTED = 130;

const POLICY_SELF = "자율개선";
const POLICY_TODO = "지시개선";
const POLICY_ALIASES = {
    auto: POLICY_SELF,
    self: POLICY_SELF,
    [POLICY_SELF]: POLICY_SELF,
    todo: POLICY_TODO,
    directed: POLICY_TODO,
    [POLICY_TODO]: POLICY_TODO
};

const DEFAULT_END_TIME = "07:00";
const DEFAULT_MODEL = "opus";
const FALLBACK_MODEL = "sonnet";
const MODEL_CHOICES = ["fable", "opus", "sonnet", "haiku"];
const DEFAULT_EFFORT = "high";
const EFFORT_LEVELS = ["low", "medium", "high", "xhigh", "max"];

const WORK_DIR_NAME = "autopilot";
const APP_DATA_DIR_NAME = "AutoPilot";
const PROJECTS_DATA_DIR_NAME = "projects";
const PROGRESS_FILE_NAME = "AUTOPILOT_PROGRESS.md";
const PROGRESS_DIR_NAME = "progress";
const STOP_FILE_NAME = "STOP";
const ROUND_OPTIONS_FILE_NAME = "ROUND_OPTIONS.json";
const LOCK_FILE_NAME = "RUNNING";
const TODO_COMPLETE_FILE_NAME = "TODO_COMPLETE";
const PROGRESS_MAX_LINES = 100;
const PROGRESS_TARGET_LINES = 60;

const MAX_STREAM_LINE_LENGTH = 1000000;
const MAX_STDERR_LENGTH = 1000000;

const ROUND_OUTCOME_COMPLETE = "완료";
const ROUND_OUTCOME_IDLE = "commit 없음";
const ROUND_OUTCOME_INTERRUPTED = "중단됨";
const ROUND_OUTCOME_RATE_LIMITED = "사용량 한도";
const ROUND_OUTCOME_TIMED_OUT = "시한 초과";

const STOP_REASON_REQUESTED = "중단 요청";

const AUTOPILOT_DEFAULTS = {
    minMinutes: 20,
    maxRounds: 60,
    maxRoundMinutes: 120,
    retryWaitMinutes: [5, 15, 30],
    maxIdleRounds: 2,
    maxTasks: 2,
    resetGraceMs: MINUTE_MS,
    logRetentionDays: 30
};

export {
    STATUS_OK,
    STATUS_FAILED,
    ERROR_CODE_AUTOPILOT_FAILED,
    ERROR_CODE_AUTOPILOT_ERROR,
    SECOND_MS,
    MINUTE_MS,
    WAIT_POLL_MS,
    REPORT_REFRESH_MS,
    EXIT_CODE_SUCCESS,
    EXIT_CODE_FAILED,
    EXIT_CODE_INTERRUPTED,
    POLICY_SELF,
    POLICY_TODO,
    POLICY_ALIASES,
    DEFAULT_END_TIME,
    DEFAULT_MODEL,
    FALLBACK_MODEL,
    MODEL_CHOICES,
    DEFAULT_EFFORT,
    EFFORT_LEVELS,
    WORK_DIR_NAME,
    APP_DATA_DIR_NAME,
    PROJECTS_DATA_DIR_NAME,
    PROGRESS_FILE_NAME,
    PROGRESS_DIR_NAME,
    STOP_FILE_NAME,
    ROUND_OPTIONS_FILE_NAME,
    LOCK_FILE_NAME,
    TODO_COMPLETE_FILE_NAME,
    PROGRESS_MAX_LINES,
    PROGRESS_TARGET_LINES,
    MAX_STREAM_LINE_LENGTH,
    MAX_STDERR_LENGTH,
    ROUND_OUTCOME_COMPLETE,
    ROUND_OUTCOME_IDLE,
    ROUND_OUTCOME_INTERRUPTED,
    ROUND_OUTCOME_RATE_LIMITED,
    ROUND_OUTCOME_TIMED_OUT,
    STOP_REASON_REQUESTED,
    AUTOPILOT_DEFAULTS
};
